### ISSUE TITLE
Segmentation Fault (71874689)

### ISSUE THREAD

**Issue by Google-Autofuzz** [WizardMac/ReadStat#114]
Hello readstat team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
readstat (tested with revision * master b7742cbf4411199a38e762c6a2b148679ccaa5fd).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
[artifacts_71874689.zip](https://github.com/WizardMac/ReadStat/files/1631286/artifacts_71874689.zip)

* `mkdir project`
* `cp Dockerfile.readstat /path/to/project/Dockerfile`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

```
INFO: Seed: 1288881163
/fuzzing/ReadStat/fuzzer: Running 1 inputs 1 time(s) each.
Running: /tmp/poc
Error processingError processingError processingASAN:DEADLYSIGNAL
=================================================================
==11==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x7f294837caa2 bp 0x7ffd3ff30670 sp 0x7ffd3ff30610 T0)
==11==The signal is caused by a READ memory access.
==11==Hint: address points to the zero page.
    #0 0x7f294837caa1 in sas7bdat_init_variable /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:512:39
    #1 0x7f294837c6c1 in sas7bdat_submit_columns /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:567:29
    #2 0x7f2948378e38 in sas7bdat_submit_columns_if_needed /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:593:23
    #3 0x7f294837b2a8 in sas7bdat_parse_page_pass2 /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:730:35
    #4 0x7f2948378bc2 in sas7bdat_parse_all_pages_pass2 /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:914:23
    #5 0x7f29483773a3 in readstat_parse_sas7bdat /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:1030:19
    #6 0x51cf57 in parse_file(char const*, int) /fuzzing/ReadStat/./fuzzer.cc:71:13
    #7 0x51d269 in fuzz_file(char const*) /fuzzing/ReadStat/./fuzzer.cc:88:3
    #8 0x51d165 in LLVMFuzzerTestOneInput /fuzzing/ReadStat/./fuzzer.cc:96:9
    #9 0x50f46c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/fuzzing/ReadStat/fuzzer+0x50f46c)
    #10 0x50ec2e in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) (/fuzzing/ReadStat/fuzzer+0x50ec2e)
    #11 0x508a8d in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*) (/fuzzing/ReadStat/fuzzer+0x508a8d)
    #12 0x509f5f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/fuzzing/ReadStat/fuzzer+0x509f5f)
    #13 0x50893c in main (/fuzzing/ReadStat/fuzzer+0x50893c)
    #14 0x7f294710a2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #15 0x41e049 in _start (/fuzzing/ReadStat/fuzzer+0x41e049)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /fuzzing/ReadStat/src/sas/readstat_sas7bdat_read.c:512:39 in sas7bdat_init_variable
==11==ABORTING

```

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team

**Comment by evanmiller** [comment]
Thanks for the report. It should be fixed in master now.

To assist in fuzzing, I have added a number of resources to ReadStat:

1. `./configure --enable-sanitizers` turns on sanitizer and sanitizer-coverage flags taken from the  Dockerfile linked above
1. `make` will create a new binary called `generate_corpus`. Running this program will use the ReadStat test suite to create a corpus of test files in `corpus/`. There is a subdirectory for each sub-format (`dta104`, `dta105`, etc.). Currently a total of 398 files are created.
1. If libFuzzer is found on the system, `make` will also create seven fuzzer targets, one for each of six file formats, and a seventh fuzzer for testing the SAS compression routines.
   * `fuzz_format_dta`
   * `fuzz_format_por`
   * `fuzz_format_sas7bcat`
   * `fuzz_format_sas7bdat`
   * `fuzz_format_sav`
   * `fuzz_format_xport`
   * `fuzz_compression_sas_rle`

For best results, each sub-directory of the corpus should be passed to the relevant fuzzer, e.g.:

* `./fuzz_format_dta corpus/dta104`
* `./fuzz_format_dta corpus/dta110`
* ...
* `./fuzz_format_xport corpus/xpt5`
* `./fuzz_format_xport corpus/xpt8`

In just a couple days of fuzzing, I have uncovered over two dozen bugs using these corpus files.

Finally, the compression fuzzer can be invoked without a corpus:

* `./fuzz_compression_sas_rle`

I will add this information to the README soon. Let me know if I can assist Google Autofuzz Team in taking advantage of these new fuzzing facilities in ReadStat. Thanks!
