### ISSUE TITLE
SAS - Creation / Modified Datetime - Platform Differences

### ISSUE THREAD

**Issue by curtisalexander** [WizardMac/ReadStat#238]
When I call the function `readstat_get_creation_time` (or `readstat_get_modified_time`) on a `sas7bdat` file, I get different values returned depending upon whether I am executing on Windows or on Linux.  

For example, using the file [somedata.sas7bdat](https://www.alanelliott.com/sas/DataSets/somedata.sas7bdat) I get the following for the creation time on Windows vs. Linux.

| Platform | Creation Time (Raw) | Creation Time (Formatted) |
|-----------|-----------------------|-------------------------------|
| Windows | 1538393035 | 2018-10-01 11:23:55 |
| Linux | 1222795436 | 2008-09-30 17:23:56 |

When opening the `somedata.sas7bdat` file in SAS itself, it notes that the creation time is **2008-09-30 17:23:56**.

Finally, I am using the latest `dev` version &mdash; abb31aabda492b6de1a51feec97d1772009e786b.

My suspicion is I have a discrepancy in the C types.  I'll continue researching myself but any thoughts about what could be the root cause?

As always, thanks for the project and your time!

**Comment by evanmiller** [comment]
I would look around here:

https://github.com/WizardMac/ReadStat/blob/69f55186ae615a14a3367ad5cd08b7829aa8f308/src/sas/readstat_sas.c#L162-L163

My guess is that Windows can't handle a negative time value (i.e. pre-1970) and returns -1 for the SAS epoch of 1 Jan 1960. We could probably update the logic to hard-code the number of seconds between 1 Jan 1960 and 1 Jan 1970 instead of computing it on the fly.

**Comment by evanmiller** [comment]
Try the fix in #240. Thanks!

**Comment by curtisalexander** [comment]
@evanmiller - Fix in #240  fixes the issue described here.  Tested same dataset on my Windows and Linux machines and the dates now match (as well as match what SAS suggests).

Hopefully it can be added to the next RC for 1.1.6.  Thanks so much!
