### ISSUE TITLE
Troubleshooting of reading sas7bdat format

### ISSUE THREAD

**Issue by sadokfire** [WizardMac/ReadStat#275]
I am investigation on reading sas7bdat files. 
I have been installed ReadStat library from vcpkg on win11.

I collected some files from Internet and I stuck on parsing of 1 file:
`https://github.com/ppham27/sas_to_csv/blob/master/test_files/supervisors.sas7bdat`

ReadStat library and tool having read file like:
![ReadStat_screen0](https://user-images.githubusercontent.com/25962605/174199074-13ce8bfb-d386-49b6-a317-020374fb49bb.png)

On DsView it's looks (https://www.oview.co.uk/dsview/):
![DsView_screen0](https://user-images.githubusercontent.com/25962605/174199138-e0653332-8955-45a6-b56a-d7be7149dff1.png)

On cppsas7bdat library, data parsed OK, but column name "JobCategory" are empty (as i undestand on that library problems with more than 1 subheaders with column metadata).
https://github.com/olivia76/cpp-sas7bdat

**Comment by evanmiller** [comment]
Hi, thank you very much for the bug report.

I've researched the issue and it appears that ReadStat is slightly confused about where to begin reading the row data.

Basically there are two classes of SAS7BDAT files. One class of file starts its data 4 bytes after the other class. I haven't found a reliable way to figure out which file is which, but ReadStat uses a couple of heuristics.

The first heuristic determines whether the file was created by Stat/Transfer. This appears to be the case with `supervisors.sas7bdat`. If the file was NOT created by Stat/Transfer, then ReadStat will "skip" the first four bytes. However, if the file WAS created by Stat/Transfer, then ReadStat uses a second heuristic. If the first four bytes of data consists of all zeroes or all spaces, then ReadStat will skip them. Otherwise, it will interpret the first four bytes as data.

In the case of `supervisors.sas7bdat`, the heuristics are failing. This file is being recognized as created by Stat/Transfer, but the first four bytes are `b00a0000`, and ReadStat is refusing to skip them.

I see a couple of options here. One is to try to hone the Stat/Transfer heuristic. The current heuristic checks to see if the self-reported SAS major version is 8 or 9 with no minor update and no patch version. The `supervisors.sas7bdat` file self-reports as being created with SAS 8.0000M0, which ReadStat assumes is really Stat/Transfer. The file also self-reports as being made on `WIN_NT`. Whatever software made it, this must be a fairly old file. We could carve out an exception for `WIN_NT` files.

The other option is to update the zero-and-space check. This could break other files, though.

A final option is just to ignore the problem. This file was created on March 18, 2000.

**Comment by sadokfire** [comment]
[evanmiller](https://github.com/evanmiller) 
Thank you very much for such a quick response and for the provided information
