### ISSUE TITLE
SAS transport files?

### ISSUE THREAD

**Issue by markdanese** [WizardMac/ReadStat#29]
The foreign package does them, but was wondering if they might be added at some point to this and then to haven.  
Thanks for writing such a useful library.

**Comment by dpastoor** [comment]
per #23 I believe this is outside of the scope of the project (for now at least)

**Comment by markdanese** [comment]
absolutely no problem.  if it ever gets elevated, here is a link to the specs, which include some C structures that might be useful.  Feel free to close this issue if that is better.
http://support.sas.com/techsup/technote/ts140.pdf
http://support.sas.com/techsup/technote/ts140_2.pdf

**Comment by evanmiller** [comment]
Thanks for the links. Closing for now, but I may revisit the issue in the future.

**Comment by hadley** [comment]
Seeing some enthusiasm for this file type on twitter: https://twitter.com/jetravis/status/783428520395608064, https://twitter.com/ImDataDriven/status/783425986549473282

**Comment by dpastoor** [comment]
I will confirm that this is the required format for the FDA - here are links http://www.fda.gov/Drugs/DevelopmentApprovalProcess/FormsSubmissionRequirements/ElectronicSubmissions/ucm085361.htm

Currently, need to use https://github.com/MangoTheCat/sasxport

If there are any FDA related questions feel free to ask (I'm a Fellow there) 

Because of the submission process, this is also a very standard data exchange format between CRO's and pharma companies as well (along with sas7bdat, which is already handled nicely in readstat/haven)

**Comment by dennisfisher** [comment]
Hadley

FDA does request files in XPT format.  If it would help, I can provide an excerpt from a boilerplate letter than they send when an NDA is submitted.  However, the SASxport package writes XPT files so further efforts may not be needed.

Dennis

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by evanmiller** [comment]
Reopening -- support for SAS Transport will be added soon.

**Comment by evanmiller** [comment]
If you'd like to test out my work-in-progress code that can read and write SAS Transport, please see #87.

**Comment by evanmiller** [comment]
The SAS transport implementation is more-or-less complete, therefore I'm closing this issue.

If you find bugs in the SAS transport reader or writer, please file a new bug.
