### ISSUE TITLE
readstat_value_is_considered_missing() confused

### ISSUE THREAD

**Issue by lionel-** [WizardMac/ReadStat#44]
Steps to reproduce:

* Import https://dl.dropboxusercontent.com/u/239966/spss_missing_bug2.sav
* Use `readstat_value_is_considered_missing(value)` in a `value_label()` handler
* The value `9` of the first column (Missing4) is misread as non missing

The value is correctly read as missing once the second column is removed.

**Comment by evanmiller** [comment]
Thanks for the bug report. It appears that this occurs when 2 columns share a set of value labels, but differ on their definitions of missing-ness. (The last definition of missing-ness overrides the others.)

I'm not sure if there's a good solution apart from "splitting" the value labels, so that each column appears to have its own set (even when they are actually shared).

**Comment by evanmiller** [comment]
Addressed in https://github.com/WizardMac/ReadStat/commit/6c61838ef555a5661dcd5f233b92d6736b9b61ec. Please update to use the new API:

```{C}
  int readstat_value_is_defined_missing(readstat_value_t value, readstat_variable_t *variable)
```

Thus you can determine missingness relative to a particular variable's rules.
