### ISSUE TITLE
Support writing Stata strings with more than 244 characters

### ISSUE THREAD

**Issue by diogocp** [WizardMac/ReadStat#45]
Stata 13 (format 117) supports strings with up to 2045 bytes.
See http://www.stata.com/help.cgi?dta_117#strings.

**Comment by evanmiller** [comment]
Thanks. This is a legitimate request but will require significant work. Currently ReadStat produces format 111. (See https://github.com/WizardMac/ReadStat/blob/master/src/readstat_dta_write.c#L291)

**Comment by wbuchanan** [comment]
@diogocp Another issue with format 117 files and later is the way that BLOBs are handled.  The values in the data entry of the file act like pointers to the location in the file where Stata can find the value.  This can get a bit complicated to parse and write correctly.  In format 118 files the way these byte location values work also shifted to using a two byte and 6 byte value stored in an 8 byte integer (in version 117 the values are 4 bytes each respectively).  It would probably require considerable effort, but files could probably be stored more efficiently if string data > 9 bytes in length (8 bytes for the location pointer and 1 byte for the value itself) are stored as strLs (assuming of course that there are duplicated values).  The reason is that the strL (BLOB) elements contain unique values from the help page:

```
If our dataset contained variable V5 equaling "third" in both
    observations,




        . list
             +--------------------------------+
             | V1   V2   V3       V4       V5 |
             |--------------------------------|
          1. |  0    1    2    first    third |
          2. |  1    2    3   second    third |
             +--------------------------------+




    they could be recorded as two separate strLs,


        <data>
            00000000 01 4000000000000000 first00 000500000000000001
            3f800000 02 4008000000000000 second  000500000000000002
        </data>
        <strls>
            GSO 00000005 0000000000000001 82 00000006 third00
            GSO 00000005 0000000000000002 82 00000006 third00
        </strls>
    
    or like this:


        <data>
            00000000 01 4000000000000000 first00 000500000000000001
            3f800000 02 4008000000000000 second  000500000000000001
        </data>
        <strls>
            GSO 00000005 0000000000000001 82 00000006 third00
        </strls>


    Note that there is only one GSO in the second form, and both observations
    refer to it by specifying (v,o) as (5,1) in <data>...</data>.  This is
    called a shared or cross-linked GSO.  Many observations can link to the
    same GSO.
```

If I knew C or understood the code base much I could try suggesting possible ways to do things, but I have no experience with the language and would probably need a lot of time to understand what was happening in the codebase.

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/ReadStat/commit/fcd69ea79ccca655a83663569a5b2fcdc0c52db5

Usage:

```{C}
  readstat_begin_writing_dta(writer, 117 /* DTA version */, ctx, row_count)
```

**Comment by evanmiller** [comment]
ReadStat contains read/write support for ASCII BLOBs as of https://github.com/WizardMac/ReadStat/commit/9e996fb619d5c41547ea3c3354d8d7e459c51669

```{C}
readstat_string_ref_t *strl = readstat_add_string_ref(writer, "Something");
readstat_insert_string_ref(writer, variable, strl);
```

The same string refs can be inserted in multiple rows and columns.
