### ISSUE TITLE
encoding problem for sas7bdat file

### ISSUE THREAD

**Issue by reikoch** [WizardMac/ReadStat#55]
Great facility for reading sas7bdat files, nearly perfect I think.

But with [https://github.com/reikoch/testfiles/blob/master/extr.sas7bdat](url), which is Shift-JIS encoded, I get on Linux:
> yy <- read_sas('extr.sas7bdat')
ReadStat: Error parsing page 0, bytes 65536-131071
Error: Failed to parse extr.sas7bdat: Invalid file, or file has unsupported features. 

:-(

**Comment by evanmiller** [comment]
Thanks, what exact settings did you use to produce this file? It appears to be an extension of Shift-JIS.

**Comment by evanmiller** [comment]
This might fix it: https://github.com/WizardMac/ReadStat/commit/c9b06df501b8435edb8560607ae9739a40a66bf3

**Comment by evanmiller** [comment]
Note you should be able to work around the issue in haven:

```{R}
read_sas('extr.sas7bdat', encoding='CP932')
```

**Comment by reikoch** [comment]
Yes, your change to CP932 works fine for me. I only subsetted "real" data, using in SAS libname statement with "OUTENCODING=SHIFT-JIS". My guess this content got copy/pasted from PC.

**Comment by evanmiller** [comment]
Thanks. There might be a minor discrepancy in SAS's versus iconv's definitions of Shift-JIS. In any event it's good to know the CP932 change fixed the issue.

When haven gets updated to use the latest commits, it should start reporting an encoding issue rather than a general parse error in these situations. Please open a new issue if you encounter any more problems like this.
